### PR TITLE
TR1-3 Fixes and Improvements

### LINKED ISSUE #259: TR3 - Improve Tile Edge Secret Handling
Add checks for secrets placed on tile edges (or within a limit of the edges) and if found, extend the trigger into neighbouring sectors where possible.

### LINKED ISSUE #333: Implement EM Serialization
Implement and test (re-)serialization of EM JSON.

### LINKED ISSUE #353: TR1 - Secret Randomizer
This should be similar to TR3, so secret artefact pickups lead to reward rooms. Secret rewards should also be randomized if selected.

- [x] Create secret model available for import
- [x] Create reward rooms
- [x] Main secret randomization logic
- [x] Add locations for Natla's Mines and Atlantis

### LINKED ISSUE #356: TR1 - Texture Randomizer

### LINKED ISSUE #360: TR1 - Environment Randomizer

### LINKED ISSUE #404: TR1-3 - Highlight triggers in wireframe mode
Add an option to highlight pads and heavy triggers in wireframe mode, otherwise floor texture hints that are ordinarily visible become lost.

### LINKED ISSUE #405: TR1 - Fuse item not randomized
The position of item 42 in Natla's Mines is not randomized when key item randomization is enabled. This was parked during initial development due to the flipmap handling in this area - environment mods should be used to allow the item to be randomized normally.

### LINKED ISSUE #406: TR3 - Coastal and Madubu spikes set incorrectly
If Coastal or Madubu end up in each other's slots, spikes are not initialised to the correct height.

### LINKED ISSUE #407: TR1-3 - Solid interactables in wireframe mode
Add an option to keep certain interactables solid in wireframe mode:
* Switches/buttons
* Keyholes/puzzle slots
* Pushblocks

### LINKED ISSUE #409: TR1 - Eggs excluded from difficulty calculation
Eggs are not included in the difficulty calculation for unarmed levels, so it's possible to end-up softlocked in the likes of Great Pyramid as it wrongly classifies the level by ignoring torso.

### LINKED ISSUE #410: TR1-3 - Filter environment mods
Currently, environment mods are filtered by `EMType`, but this is not always ideal as one type may perform two different functions (e.g. `EMAddEntityFunction` could add a new lever or a new trap). Rework the system to use tags instead so different mods of the same type can be handled separately.

### LINKED ISSUE #411: TR1-3 - Guaranteed Secret Types
Add an option that will allow at least one hard and/or glitched secret to appear in each level, where applicable.

### LINKED ISSUE #412: TR2-3 - Secret Amendments
The following secrets are incorrectly marked as glitchless easy.

Lud's room 87
RX room 102

A crawlspace in HSC room 99 is inaccessible in OG - move this secret for the time being.

Room 127 in Ice Palace when flooded has an unobtainable secret.

### LINKED ISSUE #413: Doc - Update README
Update the README with TR1 and TR3 screenshots.

### LINKED ISSUE #414: TR1 - Softlock in Obelisk
It is possible for items 16 and 18 in Obelisk to end up on the same tile, meaning the door trigger only applies for one of them and so a softlock is possible here.

### LINKED ISSUE #415: TR1-3 - Unable to insert meshes into empty levels
While this isn't generally possible/an issue in the randomizer itself, `TRMeshUtilities` will throw an index out of bounds exception if trying to insert a mesh into a level that doesn't have any.

### LINKED ISSUE #416: TR1 - Update T1M support
T1M now supports [data injection](https://github.com/rr-/Tomb1Main/pull/724); the randomizer should override injections initially as it may clash with model imports. The braid will also be supported in cutscenes, so outfit randomization should take this into consideration.

### LINKED ISSUE #417: TR1-3 - Add enemy and texture variants
Add enemy variants provided by Topixtor and Leoc1995, and texture variants provided by Ralodosmovo.

### LINKED ISSUE #418: TR1 - Unreachable item locations
It's possible for standard items to be placed on the same tiles as the static meshes in room 47 in Atlantis, as the size of these means they span more than one tile.

### LINKED ISSUE #419: Add option to reset all settings
It is not currently possible to quickly reset all settings to default without deleting the target folder and starting again. Add a suitable option for this.

### PR DESCRIPTION
**Pull request by lahm86**
## #413 README Update
Added new screenshots and updated feature list in light of the following changes. Also added a detailed "getting started" guide (USING.MD).
Closes #413.

## #416 Updated T1M Support
Runtime data injection will be supported in T1M 2.13 onwards, so preparations for this have been added, namely to override any injections as otherwise changes made by the randomizer could be overwritten.
T1M 2.13 will also support the braid in cutscenes, so this is now handled as well.
Closes #416.

## #417 TR1-3 New Enemy and Texture Variants
* Added Topixtor's flamethrower and Gunman1 enemy variants to TR2.
* Added Leoc1995's cowboy enemy variant to TR1.
* Added some new textures to TR2 and TR3 from Ralodosmovo.

Closes #417.

## #418 TR1 Unreachable Items
Fixes an issue in Atlantis where items could be placed on the same tiles as the static meshes in room 47.
Closes #418.

## #419 Reset Settings Option
The UI now has a `Reset Settings` option to quickly restore all defaults.
Closes #419.

## #353 TR1 Secret Randomization
TRGE has been updated to resolve an issue where TombATI levels always had 0 secrets defined against them, so secret randomization had no work to do effectively.
New locations have been added - the TR1 total is now 669. One location has been amended in Tomb of Qualopec (flipmap issue).
Closes #353.

## #356 TR1 Texture Randomization
Full level texture randomization is now supported, including key and secret items, plus certain enemies (all optional).
Closes #356.

## #360 TR1 Environment Randomization
Environment randomization is fully implemented, with switches, water levels, traps and puzzle/challenge areas available to be randomized. A hard mode is also available here, particularly targeted at the new puzzle/challenge areas.
Closes #360.

## #405 TR1 Mines Fuse Item
The conveyor belt fuse item is now included in key item randomization.
Closes #405.

## #409 TR1 Difficulty Calculation
Eggs were being ignored in the difficulty calculation for unarmed levels, so some softlocks were possible. All non-empty eggs that have triggers will now be included in the logic.
Closes #409.

## #414 Obelisk Softlock
Resolves a key item placement issue in Obelisk that could cause a softlock.
Closes #414.

## #406 TR3 South Pacific Spikes
Corrects the behaviour of spikes in Coastal Village and Madubu based on the level sequence.
Closes #406.

## #412 TR2-3 Secret Amendments
Locations in Ice Palace, HSC, Lud's Gate, RX Tech and Tinnos adjusted, and two additional secrets added to Coastal Village.
TR3 edge trigger handling is also improved when neighbouring sectors having different heights to the base sector.
Closes #412, closes #259.

## #404 TR1-3 Wireframe Triggers/Highlights
A new option is now available in wireframe mode to highlight pad and heavy triggers, plus death tiles to retain floor texture hints that would otherwise be lost. This also includes an option to use different wire colours for these special tiles.
In addition, other special textures will now be highlighted in wireframe mode, such as the Midas door lever combination solutions and the tiles in the Crash Site swamp.
Closes #404.

## #407 TR1-3 Solid Interactables
A new option is available for wireframe mode to make objects such as switches and pushblocks solid.
Closes #407.

## #410 TR1-3 Environment Filters
Environment modifications are now tagged to allow for easier filtering. This was mainly implemented for TR1, but TR2 has been updated to use the new method and TR3 suitably prepared.
Closes #410, closes #333.

## #411 TR1-3 Guaranteed Secrets
A new option is available for all games to guarantee secret locations - so if hard and/or glitched is selected, you will be guaranteed to get at least one in each level (where applicable).
Closes #411.

## #415 Mesh Insertion
Fixes an issue in `TRMeshUtilities` to allow inserting meshes into empty levels (not currently an issue in the randomizer itself).
Closes #415.

### CODE REVIEW

File: TREnvironmentEditor/EMEditorMapping.cs [hunk 1]
```diff
@@ -93,6 +95,10 @@ public void AlternateTextures()
             {
                 OneOf.ForEach(s => s.RemapTextures(AlternativeTextures));
             }
+            if (ConditionalOneOf != null)
+            {
+                ConditionalOneOf.ForEach(s => s.RemapTextures(AlternativeTextures));
```
Comment (chreden) [inline TREnvironmentEditor/EMEditorMapping.cs:100]: You can do `ConditionalOneOf?.ForEach(s => s.RemapTextures(AlternativeTextures));` and remove the `if != null` here, provided you have the right language version. Can do the same for the others here too.

File: TREnvironmentEditor/Helpers/EMLocationUtilities.cs [hunk 2]
```diff
@@ -0,0 +1,55 @@
...
+
+        private static int GetSectorSecret(TRRoomSector sector, FDControl floorData)
+        {
+            if (sector.FDIndex != 0)
+            {
+                if (floorData.Entries[sector.FDIndex].Find(e => e is FDTriggerEntry) is FDTriggerEntry trigger
+                    && trigger.TrigType == FDTrigType.Pickup
+                    && trigger.TrigActionList.Find(a => a.TrigAction == FDTrigAction.SecretFound) != null)
+                {
+                    return trigger.TrigActionList.First().Parameter;
```
Comment (chreden) [inline TREnvironmentEditor/Helpers/EMLocationUtilities.cs:48]: Should this be taking `.First(a => a.TrigAction == FDTrigAction.SecretFound)`? I don't know about when it's Pickup, but if there's any situations like this trigger in Tinnos it would return 44 for the secret index.
image

File: TREnvironmentEditor/EMEditorMapping.cs (hunk 1 above)
Comment (chreden) [inline TREnvironmentEditor/EMEditorMapping.cs:100]: If you're on >= C# 6.0 you can do `ConditionalOneOf?.ForEach` and remove the `if != null`

File: TREnvironmentEditor/Helpers/EMLocationUtilities.cs (hunk 2 above)
Comment (lahm86) [reply TREnvironmentEditor/Helpers/EMLocationUtilities.cs]: It's the item index we want to return here rather than the secret index - so for pickup triggers the first object entry in the action list marks the thing being picked up. I've renamed the method to make it clearer and added a check to make sure that the object entry is present instead of relying on `.First()` actually returning something.

File: TREnvironmentEditor/EMEditorMapping.cs (hunk 1 above)
Comment (lahm86) [reply TREnvironmentEditor/EMEditorMapping.cs]: Thanks, I always forget about this.

**Review by DanzaG — APPROVED** [review]
